server.port: 8082

spring:
  application:
    name: gateway
  datasource:
    url: jdbc:h2:file:./h2/gateway;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: zhou
    password: zhou
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: true
          format_sql: true
    h2:
      console:
        enabled: true
        path: /console
        settings:
          trace: false
          web-allow-others: false

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG